package robotrader.engine.event;

/**
 * Standard interface to implement to have objects 
 * that can observe a subject
 * 
 * @author xcapt
 * @author klinst
 */
public interface IObserver 
{
	/**
	 * Action to be taken when event was
	 * generated by subject.
	 * 
	 * @param evt The event
	 */
	void onUpdate(Event evt);
	
	/**
	 * Action to be taken if observed
	 * object is stopped.
	 */
	void onStopped();
	
	/**
	 * Action to be taken if observed
	 * object is started.
	 */
	void onStarted();
}
